# Generated by Django 3.1.1 on 2022-04-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0002_auto_20220419_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(to='shelf.Tag'),
        ),
    ]
