# Generated by Django 3.1.1 on 2022-04-20 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0004_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
