# Generated by Django 3.1.1 on 2022-04-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0005_auto_20220420_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.CharField(choices=[('Perishable', 'Perishable'), ('Non-perishable', 'Non-perishable'), ('Health', 'Health')], max_length=200, null=True),
        ),
    ]
